export const autocompleteLessonsData = [
  { value: "english", label: "Англійська мова" },
  { value: "german", label: "Німецька мова" },
  { value: "computer", label: "Інформатика" },
  { value: "it-tech", label: "Інформаційні технології" },
  { value: "accounting", label: "Бухгалтерський облік" },
  { value: "math", label: "Математика" },
  { value: "statistics", label: "Статистика" },
  { value: "economics", label: "Економіка" },
  { value: "chemistry", label: "Хімія" },
  { value: "biology", label: "Біологія" },
  { value: "algebra", label: "Алгебра" },
  { value: "physics", label: "Фізика" },
  { value: "history", label: "Історія" },
  { value: "ukrainian", label: "Українська мова" },
  { value: "arts", label: "Мистецтво" },
  { value: "music", label: "Музика" },
  { value: "acting", label: "Акторська майстерність" },
  { value: "painting", label: "Живопис" },
  { value: "latin", label: "Латинська мова" },
  { value: "sign", label: "Жестова мова" },
  { value: "golang", label: "Go language" },
  { value: "csharp", label: "С#" },
  { value: "corporatefinance", label: "Корпоративне фінансування" },
  { value: "geography", label: "Географія" },
  { value: "philosophy", label: "Філософія" },
  { value: "sociology", label: "Соціологія" },
  { value: "psychology", label: "Психологія" },
  { value: "social", label: "Суспільствознавство" },
  { value: "graphicdesign", label: "Графічний дизайн" },
  { value: "motiondesign", label: "Motion design" },
  { value: "photography", label: "Фотографія" },
  { value: "rlanguage", label: "R" },
  { value: "ppc", label: "PPC" },
  { value: "geometry", label: "Геометрія" },
  { value: "literature", label: "Українська література" },
  { value: "3ddesign", label: "3D дизайн" },
  { value: "videopostproduction", label: "Відео post-production" },
  { value: "tests", label: "Тести" },
  { value: "law", label: "Юридична справа" },
  { value: "base_law", label: "Основи правознавства" },
  { value: "businessmodelling", label: "Бізнес моделювання" },
  { value: "productmanagement", label: "Управління продуктом" },
  { value: "businessstrategy", label: "Бізнес стратегія" },
  { value: "businessanalytics", label: "Бізнес аналітика" },
  { value: "publicspeaking", label: "Ораторське мистецтво" },
  { value: "html", label: "HTML" },
  { value: "css", label: "CSS" },
  { value: "seo", label: "SEO" },
  { value: "smm", label: "SMM" },
  { value: "email_marketing", label: "Email маркетинг" },
  { value: "pr", label: "PR" },
  { value: "internationalbusiness", label: "Міжнародний бізнес" },
  { value: "marketingstrategy", label: "Маркетингові стратегії" },
  { value: "contentmarketing", label: "Контент маркетинг" },
  { value: "business", label: "Бізнес і управління" },
  { value: "objectivec", label: "Objective C" },
  { value: "data_science", label: "Data Science" },
  { value: "uxui", label: "UX/UI" },
  { value: "projectmanagement", label: "Управління IT проектами" },
  { value: "artificialintelligence", label: "Штучний інтелект" },
  { value: "webdevelopment", label: "Веб розробка" },
  { value: "webanalytics", label: "Веб аналітика" },
  { value: "java", label: "Java" },
  { value: "javaScript", label: "java script (js)" },
  { value: "c", label: "C" },
  { value: "swift", label: "Swift" },
  { value: "cplusplus", label: "С++" },
  { value: "rust", label: "Rust" },
]
